name: CI

on:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:

  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Node
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5 # v2
        id: app-token
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}
          owner: rickbusarow

      - name: Renovate
        uses: renovatebot/github-action@c21017a4a2fc9f42953bcc907e375a5a544557ec # v41.0.18
        with:
          configurationFile: .github/renovate-sh.json5
          token: ${{ steps.app-token.outputs.token }}
        env:
          # LOG_LEVEL: debug

  all-checks:
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    needs:
      - renovate

    steps:
      - name: require that all other jobs have passed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
