name: CI

on:
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:

  all-checks:
    runs-on: ubuntu-latest

    steps:
      - run: echo "this is a stub"
        shell: bash
