name: Renovate

on:
  schedule:
    # every 2 hours
    - cron: "0 */2 * * *"
  workflow_dispatch:
  pull_request:
    branches:
      - renovate/*
    types:
      # run when the little "click here to rebase" box is checked.
      - edited

concurrency:
  group: renovate
  cancel-in-progress: true

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@0f859bf9e69e887678d5bbfbee594437cb440ffe # v2
        id: app-token
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Renovate
        uses: renovatebot/github-action@e3c9b63dabe11d616d9a5e9c19064ec6560369c0 # v43.0.6
        with:
          configurationFile: .github/renovate-sh.json5
          token: ${{ steps.app-token.outputs.token }}
