name: Renovate

on:
  schedule:
    # every 2 hours
    - cron: "0 */2 * * *"
  workflow_dispatch:
  issues:
  pull_request:
    branches:
      - renovate/*
    types:
      # run when the little "click here to rebase" box is checked.
      - edited
  push:
    branches:
      - main

concurrency:
  group: renovate
  cancel-in-progress: true

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2
        id: app-token
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Renovate
        uses: renovatebot/github-action@8ac70de2fe55752c573155866e30735411e3b61c # v41.0.22
        with:
          configurationFile: .github/renovate-sh.json5
          token: ${{ steps.app-token.outputs.token }}
